### ISSUE TITLE
panic when running on mac

### ISSUE THREAD

**Issue by mgadzhi** [rsaarelm/magog#2]
I still can't run the game on mac os. I use stable rust 1.0.0 and run the project with 'cargo run'.
Accompanied with --verbose it gives me:

thread '\<main\>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("ERROR: 0:3: \'attribute\' : syntax error: syntax error\n")', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729
Process didn't exit successfully: `target/debug/magog` (exit code: 101)

If I run it with --release, then the next error occurs:

error: could not find rlib for: `calx_macros`
Could not compile `magog`.

**Comment by rsaarelm** [comment]
The calx_macros thing should be fixed now, thanks for reporting it.

I'm still in the dark on anything OS X related. I did some blind patching and am now explicitly setting the OpenGL version to 3.2 when creating the display and set the shaders to version 150.

Can you try again with the latest HEAD?

**Comment by mgadzhi** [comment]
Yes, the problem with calx_macros is gone. Now --release gives the same 'panic' error as debug build does.

**Comment by rsaarelm** [comment]
I just realized I can get rid of 'attribute' entirely in the shader code. Made a new commit, can you try again?

**Comment by mgadzhi** [comment]
I tried and the previous error looks fixed. Now it is:

Running `target/release/magog`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("ERROR: 0:10: Invalid call of undeclared identifier \'texture2D\'\nERROR: 0:14: Use of undeclared identifier \'tex_color\'\nERROR: 0:16: Use of undeclared identifier \'gl_FragColor\'\nERROR: 0:16: Use of undeclared identifier \'tex_color\'\nERROR: 0:16: Use of undeclared identifier \'tex_color\'\n")', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729
Process didn't exit successfully: `target/release/magog` (exit code: 101)

**Comment by rsaarelm** [comment]
We're making progress. The 'texture2D' and 'gl_FragColor' parts were indeed wrong, and my local GL drivers didn't bother to complain. Can you re-try with the latest commit?

**Comment by mgadzhi** [comment]
It worked! Thank you very much for the game and for fixing OS X problems.

**Comment by rsaarelm** [comment]
Great! Thank you for your patience.
